# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/adminer/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/angular-test/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/angular/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/backend-legacy38/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/backend-legacy39/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/backend/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/controller/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/fail2ban/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/ftp/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/neo4j/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/postgres/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/proxy/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/rabbitmq/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/redis/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/registry/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/swaggerui/"
    open-pull-reqvuests-limit: 99
    schedule:
      interval: "weekly"
