repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
  - repo: https://github.com/gitguardian/gg-shield
    rev: v1.10.8
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
