repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
  - repo: https://github.com/gitguardian/gg-shield
    rev: v1.7.3
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
