# ####################################
# USED ONLY FOR AUTOMATIC UNIT TESTS #
# ####################################

proxy:
  build: proxy

backend:
  build: backend

neo4j:
  build: neo4j

postgres:
  build: postgres

angular:
  build: angular

angular-test:
  build: angular-test

react:
  build: react

ftp:
  build: ftp

rabbitmq:
  build: rabbitmq
