# ####################################
# USED ONLY FOR AUTOMATIC UNIT TESTS #
# ####################################

proxy:
  build: proxy

backend:
  build: backend

neo4j:
  build: neo4j

postgres:
  build: postgres

mongodb:
  build: mongodb

angular:
  build: angular

angular-test:
  build: angular-test

ftp:
  build: ftp

rabbitmq:
  build: rabbitmq

adminer:
  build: adminer

swaggerui:
  build: swaggerui
