# ####################################
# USED ONLY FOR AUTOMATIC UNIT TESTS #
# ####################################
version: "3.8"

services:
  proxy:
    build:
      context: proxy
      args:
        RAPYDO_VERSION: "${RAPYDO_VERSION}"
        CURRENT_UID: "${CURRENT_UID}"
        CURRENT_GID: "${CURRENT_GID}"
    image: rapydo/proxy:${RAPYDO_VERSION}

  backend:
    build:
      context: backend
      args:
        RAPYDO_VERSION: "${RAPYDO_VERSION}"
        CURRENT_UID: "${CURRENT_UID}"
        CURRENT_GID: "${CURRENT_GID}"
    image: rapydo/backend:${RAPYDO_VERSION}

  neo4j:
    build:
      context: neo4j
      args:
        RAPYDO_VERSION: "${RAPYDO_VERSION}"
        CURRENT_UID: "${CURRENT_UID}"
        CURRENT_GID: "${CURRENT_GID}"
    image: rapydo/neo4j:${RAPYDO_VERSION}

  postgres:
    build:
      context: postgres
      args:
        RAPYDO_VERSION: "${RAPYDO_VERSION}"
        CURRENT_UID: "${CURRENT_UID}"
        CURRENT_GID: "${CURRENT_GID}"
    image: rapydo/postgres:${RAPYDO_VERSION}

  mongodb:
    build:
      context: mongodb
      args:
        RAPYDO_VERSION: "${RAPYDO_VERSION}"
        CURRENT_UID: "${CURRENT_UID}"
        CURRENT_GID: "${CURRENT_GID}"
    image: rapydo/mongodb:${RAPYDO_VERSION}

  angular:
    build:
      context: angular
      args:
        RAPYDO_VERSION: "${RAPYDO_VERSION}"
        CURRENT_UID: "${CURRENT_UID}"
        CURRENT_GID: "${CURRENT_GID}"
    image: rapydo/angular:${RAPYDO_VERSION}

  angular-test:
    build:
      context: angular-test
      args:
        RAPYDO_VERSION: "${RAPYDO_VERSION}"
        CURRENT_UID: "${CURRENT_UID}"
        CURRENT_GID: "${CURRENT_GID}"
    image: rapydo/angular-test:${RAPYDO_VERSION}

  ftp:
    build:
      context: ftp
      args:
        RAPYDO_VERSION: "${RAPYDO_VERSION}"
        CURRENT_UID: "${CURRENT_UID}"
        CURRENT_GID: "${CURRENT_GID}"
    image: rapydo/ftp:${RAPYDO_VERSION}

  rabbitmq:
    build:
      context: rabbitmq
      args:
        RAPYDO_VERSION: "${RAPYDO_VERSION}"
        CURRENT_UID: "${CURRENT_UID}"
        CURRENT_GID: "${CURRENT_GID}"
    image: rapydo/rabbitmq:${RAPYDO_VERSION}

  adminer:
    build:
      context: adminer
      args:
        RAPYDO_VERSION: "${RAPYDO_VERSION}"
        CURRENT_UID: "${CURRENT_UID}"
        CURRENT_GID: "${CURRENT_GID}"
    image: rapydo/adminer:${RAPYDO_VERSION}

  swaggerui:
    build:
      context: swaggerui
      args:
        RAPYDO_VERSION: "${RAPYDO_VERSION}"
        CURRENT_UID: "${CURRENT_UID}"
        CURRENT_GID: "${CURRENT_GID}"
    image: rapydo/swaggerui:${RAPYDO_VERSION}

  registry:
    build:
      context: registry
      args:
        RAPYDO_VERSION: "${RAPYDO_VERSION}"
        CURRENT_UID: "${CURRENT_UID}"
        CURRENT_GID: "${CURRENT_GID}"
    image: rapydo/registry:${RAPYDO_VERSION}
