name: Build

on:
  push:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 8

    env:
      RAPYDO_VERSION: "2.0"

    strategy:
      matrix:
        service:
          [
            backend,
            angular,
            angular-test,
            proxy,
            neo4j,
            rabbitmq,
            postgres,
            mongodb,
            ftp,
            adminer,
            swaggerui,
            registry,
          ]

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build the Docker image
        run: |
          docker buildx version
          echo "RAPYDO_VERSION=${RAPYDO_VERSION}" > .env
          echo "CURRENT_UID=1000" >> .env
          echo "CURRENT_GID=1000" >> .env
          docker-compose config > docker-compose-2.yml
          docker buildx bake --file docker-compose-2.yml --push ${{ matrix.service }}
